//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kd2020
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tourfirmEntities : DbContext
    {
        private static tourfirmEntities _context;
        public tourfirmEntities()
            : base("name=tourfirmEntities")
        {
        }
       
        public static tourfirmEntities GetContext()
        {
            if (_context == null)
                _context = new tourfirmEntities();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<clients> clients { get; set; }
        public virtual DbSet<country> country { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<staffs> staffs { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tickets> tickets { get; set; }
        public virtual DbSet<tours> tours { get; set; }
        public virtual DbSet<towns> towns { get; set; }
    }
}
