//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kd2020
{
    using System;
    using System.Collections.Generic;
    
    public partial class tickets
    {
        public int ticketId { get; set; }
        public int tourId { get; set; }
        public int clientId { get; set; }
        public int staffId { get; set; }
    
        public virtual clients clients { get; set; }
        public virtual staffs staffs { get; set; }
        public virtual tours tours { get; set; }
    }
}
