//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kd2020
{
    using System;
    using System.Collections.Generic;
    
    public partial class tours
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tours()
        {
            this.tickets = new HashSet<tickets>();
        }
    
        public int tourId { get; set; }
        public int townId { get; set; }
        public int daysQnt { get; set; }
        public System.DateTime dateDeparture { get; set; }
        public System.DateTime dateArrive { get; set; }
        public decimal tourPrice { get; set; }
        public int ticketQnt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tickets> tickets { get; set; }
        public virtual towns towns { get; set; }
    }
}
